In [1]:
import os
import pickle
import logging
import numpy as np
import torch
from cryodrgn import lie_tools
import random

In [12]:
workdir = '/hpc/home/ds672/master/aux_functions/'
my_orig_poses_pkl = 'pkl_files/mine_cryosparc_P59_J9_004_particles.pkl'
my_modify_poses_pkl = 'pkl_files/mine_cryosparc_P59_J9_004_particles_20_pixels_variation.pkl' #Generada modificando las poses originales (.cs) y cambiandoles el nombre



In [24]:
with open(my_orig_poses_pkl, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[  2.95   9.85]
 [-15.25  -3.15]
 [-15.65  -7.75]
 ...
 [-31.55   0.65]
 [ 12.55   0.25]
 [  1.75 -13.45]]


In [25]:
with open(my_modify_poses_pkl, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[-0.00953125 -0.02234375]
 [-0.10078125  0.00890625]
 [-0.03015625 -0.06171875]
 ...
 [-0.07359375  0.03640625]
 [-0.00453125 -0.02109375]
 [-0.01640625 -0.08265625]]


In [28]:
aes = 'cryosparc_P4_J33_004_particles_0rot_0trans_drgn.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[ 0.00859375  0.02453125]
 [-0.06484375  0.00484375]
 [-0.05453125 -0.00984375]
 ...
 [-0.09328125 -0.00984375]
 [ 0.03515625 -0.00265625]
 [-0.00515625 -0.04515625]]


In [29]:
aes = 'cryosparc_P4_J33_004_particles_0rot_10trans_drgn.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[ 0.02109375  0.03078125]
 [-0.03359375 -0.02328125]
 [-0.04515625  0.01828125]
 ...
 [-0.12453125  0.02140625]
 [ 0.01640625 -0.02453125]
 [ 0.00109375 -0.01703125]]


In [30]:
aes = 'cryosparc_P4_J33_004_particles.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[  2.75   7.85]
 [-20.75   1.55]
 [-17.45  -3.15]
 ...
 [-29.85  -3.15]
 [ 11.25  -0.85]
 [ -1.65 -14.45]]


In [36]:
aes = 'cryosparc_P4_J33_004_particles_0rot_10trans.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[  6.75         9.8499999 ]
 [-10.75        -7.45000005]
 [-14.45000076   5.8499999 ]
 ...
 [-39.85000038   6.8499999 ]
 [  5.25        -7.85000002]
 [  0.35000002  -5.44999981]]


In [35]:
aes = 'cryosparc_P4_J33_004_particles_50_pixels_variation.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[ 16.75   5.85]
 [-44.75  -2.45]
 [-49.45   4.85]
 ...
 [ 18.15 -15.15]
 [-12.75  35.15]
 [-50.65  10.55]]
