In [1]:
import os
import pickle
import logging
import numpy as np
import torch
from cryodrgn import lie_tools
import random

In [12]:
workdir = '/hpc/home/ds672/master/aux_functions/'
my_orig_poses_pkl = 'pkl_files/mine_cryosparc_P59_J9_004_particles.pkl'
my_modify_poses_pkl = 'pkl_files/mine_cryosparc_P59_J9_004_particles_20_pixels_variation.pkl' #Generada modificando las poses originales (.cs) y cambiandoles el nombre



In [24]:
with open(my_orig_poses_pkl, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[  2.95   9.85]
 [-15.25  -3.15]
 [-15.65  -7.75]
 ...
 [-31.55   0.65]
 [ 12.55   0.25]
 [  1.75 -13.45]]


In [25]:
with open(my_modify_poses_pkl, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[-0.00953125 -0.02234375]
 [-0.10078125  0.00890625]
 [-0.03015625 -0.06171875]
 ...
 [-0.07359375  0.03640625]
 [-0.00453125 -0.02109375]
 [-0.01640625 -0.08265625]]


In [28]:
aes = 'cryosparc_P4_J33_004_particles_0rot_0trans_drgn.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[ 0.00859375  0.02453125]
 [-0.06484375  0.00484375]
 [-0.05453125 -0.00984375]
 ...
 [-0.09328125 -0.00984375]
 [ 0.03515625 -0.00265625]
 [-0.00515625 -0.04515625]]


In [29]:
aes = 'cryosparc_P4_J33_004_particles_0rot_10trans_drgn.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[ 0.02109375  0.03078125]
 [-0.03359375 -0.02328125]
 [-0.04515625  0.01828125]
 ...
 [-0.12453125  0.02140625]
 [ 0.01640625 -0.02453125]
 [ 0.00109375 -0.01703125]]


In [30]:
aes = 'cryosparc_P4_J33_004_particles.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[  2.75   7.85]
 [-20.75   1.55]
 [-17.45  -3.15]
 ...
 [-29.85  -3.15]
 [ 11.25  -0.85]
 [ -1.65 -14.45]]


In [36]:
aes = 'cryosparc_P4_J33_004_particles_0rot_10trans.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[  6.75         9.8499999 ]
 [-10.75        -7.45000005]
 [-14.45000076   5.8499999 ]
 ...
 [-39.85000038   6.8499999 ]
 [  5.25        -7.85000002]
 [  0.35000002  -5.44999981]]


In [35]:
aes = 'cryosparc_P4_J33_004_particles_50_pixels_variation.pkl'

with open(aes, 'rb') as file:
    data = pickle.load(file)[1]

print(data)

[[ 16.75   5.85]
 [-44.75  -2.45]
 [-49.45   4.85]
 ...
 [ 18.15 -15.15]
 [-12.75  35.15]
 [-50.65  10.55]]


In [1]:
workdir = '/nfs/bartesaghilab2/ds672/empiar10076'
dir1 = '2023_10_30_output_tutorial_downsampling_256_z_8'
dir2 = '2023_11_16_output_tutorial_downsampling_256_z_8_myposes_iteration2_filtered_refinament'

In [7]:
import os
import pickle

path1 = os.path.join(workdir,dir1)
path2 = os.path.join(workdir,dir2)

In [21]:
list1 = ['z.47.pkl','z.48.pkl','z.49.pkl']
list2 = ['z.50.pkl','z.51.pkl','z.52.pkl']

for i in list1:
    with open(os.path.join(path1,i), 'rb') as file:
        data = pickle.load(file)
    print(data[0])

for i in list2:
    with open(os.path.join(path2,i), 'rb') as file:
        data = pickle.load(file)
    print(data[0])
 

[-0.5806772   2.9857981  -1.4895264   0.45664987  2.23082    -1.9685698
  4.1320343   1.8610803 ]
[-0.39568976  2.553999   -1.274775    0.34922326  2.2788665  -2.3655627
  4.2160554   1.4055042 ]
[-0.64940447  2.9664845  -1.6622531   0.5239396   2.4412818  -2.0587168
  4.13726     1.9111092 ]
[ 1.6408249   0.9993216  -0.94865716 -0.24437915 -0.2951821  -1.0699033
  2.4596934   1.595293  ]
[ 1.6857738   1.7172734  -1.3465561   0.53758395  0.02321222 -2.0458035
  3.778265    2.2375338 ]
[ 1.7433841   1.4147276  -1.5931851   0.46095124 -0.4838981  -1.6090684
  3.4077451   1.649601  ]


In [22]:
list1 = ['weights.47.pkl','z.48.pkl','z.49.pkl']
list2 = ['z.50.pkl','z.51.pkl','z.52.pkl']

for i in list1:
    with open(os.path.join(path1,i), 'rb') as file:
        data = pickle.load(file)
    print(data[0])

for i in list2:
    with open(os.path.join(path2,i), 'rb') as file:
        data = pickle.load(file)
    print(data[0])

UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

In [23]:
import torch
import pickle

def load_checkpoint(model, optimizer, checkpoint_path):
    checkpoint = torch.load(checkpoint_path)

    # Load model weights
    model.load_state_dict(checkpoint['model_state_dict'])

    # Load optimizer state
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])

    # Additional information if needed
    epoch = checkpoint['epoch']

    return model, optimizer, epoch

def load_z(z_path):
    with open(z_path, 'rb') as f:
        z_mu = pickle.load(f)
        z_logvar = pickle.load(f)
    
    return z_mu, z_logvar

# Example usage
model = YourModelClass()  # Replace YourModelClass with the actual class of your model
optimizer = torch.optim.Adam(model.parameters(), lr=your_learning_rate)  # Adjust the optimizer accordingly
checkpoint_path = 'path/to/weights.pkl'
z_path = 'path/to/z.pkl'

model, optimizer, epoch = load_checkpoint(model, optimizer, checkpoint_path)
z_mu, z_logvar = load_z(z_path)

# Now you have loaded the model, optimizer, and the z values
# You can use them as needed in your application


NameError: name 'YourModelClass' is not defined